# Generated by Django 5.1.1 on 2025-01-11 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='event_registration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.eventregistration'),
        ),
    ]
