# Generated by Django 5.1.1 on 2024-12-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_mpesatransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'verbose_name': 'M-PESA Payment', 'verbose_name_plural': 'M-PESA Payments'},
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='event_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventregistration'),
        ),
    ]
