# Generated by Django 5.1.1 on 2025-01-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_mpesatransaction_event_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='event_registration',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
